# Generated by Django 5.2.8 on 2026-01-12 11:08

import manuscripts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=manuscripts.models.manuscript_upload_path),
        ),
    ]
