# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_manuscript_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('selected_text', models.TextField(blank=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='manuscripts.manuscript')),
            ],
        ),
    ]
