# Generated by Django 5.2.8 on 2026-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
