# Generated by Django 5.2.8 on 2025-12-06 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='Unknown Author', max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('FANTASY', 'Fantasy'), ('SCIENCE_FICTION', 'Science Fiction'), ('ROMANCE', 'Romance'), ('THRILLER', 'Thriller'), ('MYSTERY', 'Mystery'), ('SELF_HELP', 'Self-Help'), ('BUSINESS', 'Business'), ('PROGRAMMING', 'Programming'), ('CLASSIC', 'Classic'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('seller_id', models.CharField(max_length=255)),
                ('seller_name', models.CharField(default='Anonymous Seller', max_length=255)),
                ('status', models.CharField(choices=[('LISTED', 'Listed'), ('RECEIVED', 'Received by Platform'), ('SOLD', 'Sold'), ('PAID', 'Paid Out')], default='LISTED', max_length=20)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.listing')),
            ],
        ),
    ]
