# Generated by Django 5.2.8 on 2025-12-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='language',
            field=models.CharField(choices=[('RO', 'Română'), ('EN', 'English'), ('FR', 'Français'), ('DE', 'Deutsch'), ('ES', 'Español'), ('IT', 'Italiano'), ('OTHER', 'Other')], default='RO', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='pages',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
